DATA_DIR = "data"
VAL_DIR = "data\\val"
TRAIN_DIR = "data\\train"
HD_TRAIN_DIR = "hd_data\\train"
HD_VAL_DIR = "hd_data\\val"
KANJI_LIST = "kanji.txt"
FONT_DIR = "C:\\Windows\\Fonts"
FONT_GOTHIC = "msgothic.ttc"
FONT_ARIAL = "ARIALUNI.TTF"
FONTS = ["msmincho.ttc"] #['AdobeFangsongStd-Regular.otf', 'AdobeFanHeitiStd-Bold.otf', 'AdobeGothicStd-Bold.otf', 'AdobeHeitiStd-Regular.otf', 'AdobeKaitiStd-Regular.otf', 'AdobeMingStd-Light.otf', 'AdobeMyungjoStd-Medium.otf', 'AdobeSongStd-Light.otf', 'ARIALUNI.TTF', 'AsobiMemogaki-Regular-1-01.ttf', 'batang.ttc', 'GN-Koharuiro_Sunray.ttf', 'gulim.ttc', 'Hosohuwafont.ttf', 'irohamaru-mikami-Regular.ttf', 'kaiu.ttf', 'KozGoPr6N-Bold.otf', 'KozGoPr6N-ExtraLight.otf', 'KozGoPr6N-Heavy.otf', 'KozGoPr6N-Light.otf', 'KozGoPr6N-Medium.otf', 'KozGoPr6N-Regular.otf', 'KozGoPro-Bold.otf', 'KozGoPro-ExtraLight.otf', 'KozGoPro-Heavy.otf', 'KozGoPro-Light.otf', 'KozGoPro-Medium.otf', 'KozGoPro-Regular.otf', 'KozMinPr6N-Bold.otf', 'KozMinPr6N-ExtraLight.otf', 'KozMinPr6N-Heavy.otf', 'KozMinPr6N-Light.otf', 'KozMinPr6N-Medium.otf', 'KozMinPr6N-Regular.otf', 'KozMinPro-Bold.otf', 'KozMinPro-ExtraLight.otf', 'KozMinPro-Heavy.otf', 'KozMinPro-Light.otf', 'KozMinPro-Medium.otf', 'KozMinPro-Regular.otf', 'Mamelon.otf', 'meiryo.ttc', 'meiryob.ttc', 'mingliu.ttc', 'MSJH.TTC', 'msjh.ttf', 'MSJHBD.TTC', 'msjhbd.ttf', 'msmincho.ttc', 'MSYH.TTC', 'msyh.ttf', 'MSYHBD.TTC', 'msyhbd.ttf', 'ShigotoMemogaki-Regular-1-01.ttf', 'simfang.ttf', 'simhei.ttf', 'simkai.ttf', 'simsun.ttc', 'SourceHanSerif-Regular.otf', 'TAKUMISFONT_L.ttf']
VAL_FONTS = ['msgothic.ttc']
FONT_SIZE = 30
COLOR = (255, 255, 255)
TEXT_OFFSET = (4, 2)
IMAGE_SIZE = (35, 35)
BACKGROUND = (0, 0, 0)
LEARNING_RATE = 0.01
BATCH_SIZE = 64
NUM_AUGMENTATIONS = 1
EPOCHS = 25
